/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "background": "#f8f9ff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#93ccff",
        "on-primary": "#ffffff",
        "outline": "#72777e",
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
        "secondary-fixed-dim": "#9bccf6",
        "outline-variant": "#c2c7ce",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004b73",
        "secondary": "#2f6388",
        "inverse-surface": "#213145",
        "surface-container": "#e5eeff",
        "tertiary-fixed": "#cce5ff",
        "inverse-primary": "#a4caf1",
        "on-surface-variant": "#42474e",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#001d32",
        "on-tertiary-fixed": "#001d31",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#cbe6ff",
        "on-primary-container": "#81a7cc",
        "primary-container": "#0f3c5c",
        "on-secondary-container": "#275c81",
        "on-error-container": "#93000a",
        "primary": "#00263f",
        "on-secondary-fixed": "#001e30",
        "on-background": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#3b6284",
        "tertiary": "#00263e",
        "on-primary-fixed-variant": "#214a6a",
        "tertiary-container": "#003d5f",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#0e4b6e",
        "surface-variant": "#d3e4fe",
        "on-surface": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "primary-fixed-dim": "#a4caf1",
        "secondary-container": "#a3d4fe",
        "on-tertiary-container": "#4babf0",
        "primary-fixed": "#cee5ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit-xl": "1.5rem",
        "gutter-mobile": "0.75rem",
        "unit-2xs": "0.125rem",
        "unit-md": "0.75rem",
        "unit-xs": "0.25rem",
        "a4-ratio-width": "210mm",
        "unit-2xl": "2rem",
        "unit-lg": "1.25rem",
        "a4-ratio-height": "297mm",
        "unit-sm": "0.5rem",
        "gutter-desktop": "1.5rem",
        "unit-base": "1rem",
        "max-sheet-width": "1280px"
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "badge-label": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "label-numeric": ["JetBrains Mono"],
        "title-base": ["Inter"],
        "code-dense": ["JetBrains Mono"],
        "display-lg": ["Inter"]
      },
      fontSize: {
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["13px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "badge-label": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "body-lg": ["15px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "display-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-numeric": ["13px", { "lineHeight": "18px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "title-base": ["15px", { "lineHeight": "22px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "code-dense": ["12px", { "lineHeight": "16px", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
